# Generated by Django 4.0.2 on 2022-02-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreadings',
            old_name='sensor_type',
            new_name='Sensor_type',
        ),
    ]
