# Generated by Django 4.0.2 on 2022-02-11 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_sensor_type_sensorreadings_sensor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreadings',
            old_name='Sensor_type',
            new_name='sensor_type',
        ),
    ]
